import { preguntas, type Pregunta, type Unidad } from "./preguntas";

/**
 * Recorrido de lectura: las páginas de los PDFs en orden y, después de cada una,
 * las preguntas que salen de ella. Las páginas sin contenido (portadas, índices,
 * bibliografía) no figuran. Las imágenes se generan con scripts/generar-diapositivas.py.
 */
export type Doc = "u1" | "u2a" | "u2b" | "u3" | "u4" | "u4c";

export const DOCS: Record<Doc, { unidad: Unidad; nombre: string; corto: string; pagina: string; vertical: boolean }> = {
  u1: { unidad: 1, nombre: "Unidad 1 · Contenidos", corto: "U1", pagina: "Pág.", vertical: true },
  u2a: { unidad: 2, nombre: "Unidad 2 · Parte 1", corto: "U2 P1", pagina: "Diap.", vertical: false },
  u2b: { unidad: 2, nombre: "Unidad 2 · Parte 2", corto: "U2 P2", pagina: "Diap.", vertical: false },
  u3: { unidad: 3, nombre: "Unidad 3", corto: "U3", pagina: "Diap.", vertical: false },
  u4: { unidad: 4, nombre: "Unidad 4", corto: "U4", pagina: "Diap.", vertical: false },
  u4c: { unidad: 4, nombre: "Unidad 4 · Conceptos cartográficos (IGN)", corto: "U4 IGN", pagina: "Pág.", vertical: true },
};

export type Pagina = {
  doc: Doc;
  n: number;
  unidad: Unidad;
  src: string;
  /** "U1 · Pág. 3" */
  etiqueta: string;
  preguntas: Pregunta[];
};

// [documento, página, ids de las preguntas en el orden en que se responden]
const PAGINAS: [Doc, number, string[]][] = [
  // Unidad 1 (revisada). Se saltea la pág. 15: anexo CORINE
  ["u1", 1, ["u1-def", "u1-preguntas-sig", "c-categorias", "c-cat-localizacion", "c-cat-atributos", "c-cat-morfometria", "c-cat-analisis"]],
  ["u1", 2, ["u1-analisis", "u1-rutas", "c-capacidades", "c-capacidades-vf", "p25-cap-relacion", "p25-cap-clientes", "p25-cap-cartografia", "v25-cap-casas", "v25-cap-suelo"]],
  ["u1", 3, ["r-ncgia", "u1-aplicaciones", "u1-antropica", "c-papeles", "c-papel-caso-particular", "c-papel-brotes", "c-papel-hospital", "c-papel-transporte", "c-papel-municipio", "c-papel-difusion", "p25-vf-sig"]],
  ["u1", 4, ["c-factores-clasificacion", "c-recursos-naturales", "c-riesgos", "c-dos-factores", "u1-etapas"]],
  ["u1", 5, ["u1-snow", "u1-cgis"]],
  ["u1", 6, ["r-symap-grid"]],
  ["u1", 7, []],
  ["u1", 8, []],
  ["u1", 9, []],
  ["u1", 10, []],
  ["u1", 11, []],
  ["u1", 12, []],
  ["u1", 13, ["u1-componentes", "u1-hardware", "u1-software", "u1-datos-importante"]],
  ["u1", 14, ["u1-personal-vf", "c-motor-sig", "c-personal-perfiles", "u1-metodos", "c-elementos-sistema", "c-olaya"]],
  // Unidad 2 · parte 1 (revisada). Se saltean la portada, el índice y las fuentes (diap. 1, 2 y 76)
  ["u2a", 3, ["r-diferenciador"]],
  ["u2a", 4, ["u2-componentes-info"]],
  ["u2a", 5, ["r-parcela"]],
  ["u2a", 6, ["r-compleja"]],
  ["u2a", 7, []],
  ["u2a", 8, []],
  ["u2a", 9, ["u2-division-horizontal"]],
  ["u2a", 10, ["r-categorias", "p25-vf-division", "v25-vertical"]],
  ["u2a", 11, []],
  ["u2a", 12, []],
  ["u2a", 13, ["u2-capas-mapa"]],
  ["u2a", 14, []],
  ["u2a", 15, ["u2-capas"]],
  ["u2a", 16, []],
  ["u2a", 17, ["u2-problema"]],
  ["u2a", 18, ["r-mayor-abstraccion", "r-menor-abstraccion", "u2-niveles"]],
  ["u2a", 19, ["r-paradigmas", "u2-dimensiones", "u2-regla-oro"]],
  ["u2a", 20, []],
  ["u2a", 21, ["u2-campo-def"]],
  ["u2a", 22, []],
  ["u2a", 23, ["u2-viento", "r-termino-vectorial"]],
  ["u2a", 24, ["u2-origen"]],
  ["u2a", 25, ["u2-discretas", "c-cruce-calles", "r-nominal", "u2-escalares"]],
  ["u2a", 26, ["u2-asociacion"]],
  ["u2a", 27, ["u2-elev-tin", "r-elev-malla", "p25-raster-cual"]],
  ["u2a", 28, ["u2-red-raster"]],
  ["u2a", 29, []],
  ["u2a", 30, []],
  ["u2a", 31, ["u2-elev-curvas"]],
  ["u2a", 32, []],
  ["u2a", 33, ["u2-raster-espacio", "p25-raster-pixel"]],
  ["u2a", 34, ["u2-sistematicidad"]],
  ["u2a", 35, ["u2-definir-raster", "e-raster-elev"]],
  ["u2a", 36, []],
  ["u2a", 37, ["u2-malla-coords", "e-raster-coord"]],
  ["u2a", 38, ["u2-resolucion-calc", "e-raster-area"]],
  ["u2a", 39, []],
  ["u2a", 40, ["u2-resolucion"]],
  ["u2a", 41, ["u2-raster-analisis"]],
  ["u2a", 42, ["r-imagenes"]],
  ["u2a", 43, []],
  ["u2a", 44, ["u2-primitivas"]],
  ["u2a", 45, ["u2-ciudad"]],
  ["u2a", 46, ["r-forma-primitiva", "u2-vector-campos"]],
  ["u2a", 47, []],
  ["u2a", 48, ["u2-tematica-enlace", "r-raster-sin-bd"]],
  ["u2a", 49, ["u2-tipo-analisis-2", "r-analisis-espacial", "u2-tipo-analisis"]],
  ["u2a", 50, []],
  ["u2a", 51, ["r-topo-reglas"]],
  ["u2a", 52, ["u2-topologia-def", "r-cartografica"]],
  ["u2a", 53, []],
  ["u2a", 54, ["u2-topo-importancia"]],
  ["u2a", 55, []],
  ["u2a", 56, ["u2-redes", "p25-redes"]],
  ["u2a", 57, ["r-topo-calidad"]],
  ["u2a", 58, ["u2-edicion"]],
  ["u2a", 59, ["u2-topologia-raster"]],
  ["u2a", 60, []],
  ["u2a", 61, []],
  ["u2a", 62, ["u2-spaghetti"]],
  ["u2a", 63, ["u2-sin-topo-razones"]],
  ["u2a", 64, ["u2-areas-influencia"]],
  ["u2a", 65, ["u2-diccionario"]],
  ["u2a", 66, ["u2-dime"]],
  ["u2a", 67, ["u2-arconodo-elementos"]],
  ["u2a", 68, ["u2-arconodo-tabla"]],
  ["u2a", 69, ["r-dime-arconodo"]],
  ["u2a", 70, ["r-conectividad", "r-adyacencia", "p25-comp-conectividad", "v25-comp-adyacencia"]],
  ["u2a", 71, ["u2-relaciones", "r-inclusion"]],
  ["u2a", 72, ["u2-matriz-sintesis"]],
  ["u2a", 73, ["u2-imprecision"]],
  ["u2a", 74, ["u2-no-idoneo"]],
  ["u2a", 75, ["u2-cuando-usar", "u2-cuando-vectorial"]],
  // Unidad 2 · parte 2 (revisada). Se saltean la portada, los títulos de sección y el enlace a PostGIS (diap. 1, 2, 27 y 30)
  ["u2b", 3, []],
  ["u2b", 4, ["u2b-necesidades"]],
  ["u2b", 5, []],
  ["u2b", 6, []],
  ["u2b", 7, ["c-compresion"]],
  ["u2b", 8, []],
  ["u2b", 9, ["u2b-bip", "u2b-bil", "e-bsq"]],
  ["u2b", 10, ["u2b-vectorial"]],
  ["u2b", 11, ["p25-vf-indices", "v25-indices-discretos"]],
  ["u2b", 12, ["u2b-indices"]],
  ["u2b", 13, ["u2b-indexacion"]],
  ["u2b", 14, ["u2b-rtree"]],
  ["u2b", 15, ["r-formatos-vector"]],
  ["u2b", 16, []],
  ["u2b", 17, ["r-formatos-raster"]],
  ["u2b", 18, []],
  ["u2b", 19, ["u2b-shapefile"]],
  ["u2b", 20, ["u2b-prj", "p25-vf-shapefile", "v25-prj"]],
  ["u2b", 21, ["r-gml"]],
  ["u2b", 22, []],
  ["u2b", 23, ["r-kml"]],
  ["u2b", 24, ["u2b-kml"]],
  ["u2b", 25, []],
  ["u2b", 26, ["u2b-geojson"]],
  ["u2b", 28, []],
  ["u2b", 29, ["u2b-sdbms", "r-tablas-gd"]],
  ["u2b", 31, []],
  ["u2b", 32, ["r-postgis"]],
  ["u2b", 33, []],
  ["u2b", 34, ["r-sfs"]],
  // Unidad 3 (revisada). Se saltean la portada, la ilustración de apertura y los títulos de sección (diap. 1, 2, 7, 14, 37, 45 y 69)
  ["u3", 3, ["r-geodesia-def"]],
  ["u3", 4, ["u3-geodesia-tipos"]],
  ["u3", 5, []],
  ["u3", 6, ["u3-cartografia-def"]],
  ["u3", 8, ["r-edicion"]],
  ["u3", 9, ["u3-problemas-cartografia", "c-generalizacion-def"]],
  ["u3", 10, []],
  ["u3", 11, []],
  ["u3", 12, ["e-escala-tipo", "p25-comp-ampliacion", "v25-comp-reduccion"]],
  ["u3", 13, ["u3-escala-tipos", "e-escala-representaciones", "u3-escala-unidad", "e-escala-2cm", "u3-escala-calc", "e-escala-mapa", "e-escala-grafica", "e-escala-comparar"]],
  ["u3", 15, []],
  ["u3", 16, ["u3-forma"]],
  ["u3", 17, []],
  ["u3", 18, []],
  ["u3", 19, ["u3-por-que-forma"]],
  ["u3", 20, []],
  ["u3", 21, ["u3-geoide", "v25-geoide"]],
  ["u3", 22, ["u3-geoide-razon"]],
  ["u3", 23, []],
  ["u3", 24, []],
  ["u3", 25, []],
  ["u3", 26, ["u3-geoide-insuficiente"]],
  ["u3", 27, ["r-elipsoide-def", "p25-vf-elipsoide"]],
  ["u3", 28, ["r-semiejes", "u3-elipse-params"]],
  ["u3", 29, []],
  ["u3", 30, ["e-elipsoide-b"]],
  ["u3", 31, []],
  ["u3", 32, ["u3-capas-tierra"]],
  ["u3", 33, ["r-no-coinciden"]],
  ["u3", 34, []],
  ["u3", 35, []],
  ["u3", 36, ["u3-latlon", "p25-vf-coord"]],
  ["u3", 38, ["u3-sistema-def"]],
  ["u3", 39, ["u3-local-vf"]],
  ["u3", 40, ["u3-datum"]],
  ["u3", 41, []],
  ["u3", 42, ["u3-global"]],
  ["u3", 43, []],
  ["u3", 44, ["u3-marco"]],
  ["u3", 46, ["r-proyeccion-def"]],
  ["u3", 47, []],
  ["u3", 48, ["u3-distorsiones"]],
  ["u3", 49, ["u3-escala-nominal"]],
  ["u3", 50, []],
  ["u3", 51, ["r-tipos-proyecciones"]],
  ["u3", 52, ["r-conformes"]],
  ["u3", 53, ["r-equivalentes", "u3-mercator", "p25-equivalentes"]],
  ["u3", 54, ["u3-equidistante"]],
  ["u3", 55, ["u3-desarrollables", "u3-contacto"]],
  ["u3", 56, []],
  ["u3", 57, ["u3-conicas"]],
  ["u3", 58, ["u3-cilindricas"]],
  ["u3", 59, []],
  ["u3", 60, ["u3-aspecto"]],
  ["u3", 61, []],
  ["u3", 62, ["u3-perspectivas", "r-ortografica"]],
  ["u3", 63, ["r-epsg-problema"]],
  ["u3", 64, ["r-crs-srs", "u3-reproyeccion"]],
  ["u3", 65, ["u3-epsg-def"]],
  ["u3", 66, []],
  ["u3", 67, ["r-epsg-4326"]],
  ["u3", 68, ["u3-epsg-4326"]],
  ["u3", 70, ["p25-vf-posgar"]],
  ["u3", 71, ["u3-tyson"]],
  ["u3", 72, []],
  ["u3", 73, ["r-utm-ventaja"]],
  ["u3", 74, ["u3-utm", "e-utm-zona"]],
  ["u3", 75, ["u3-argentina", "r-faja-ancho", "u3-chaco"]],
  ["u3", 76, ["e-gk-faja"]],
  ["u3", 77, ["u3-proj4-posgar", "e-gk-x"]],
  ["u3", 78, []],
  ["u3", 79, ["r-mismo-punto"]],
  // Unidad 4 (revisada). Se saltean la portada, el índice, los títulos de transición y las fuentes (diap. 1, 2, 15, 32 y 86)
  ["u4", 3, ["q4-visualizar", "q4-dos-tareas"]],
  ["u4", 4, ["q4-operador-cartografo"]],
  ["u4", 5, ["q4-exactitud-estetica"]],
  ["u4", 6, []],
  ["u4", 7, ["q4-hay-que-saber"]],
  ["u4", 8, ["q4-elementos-elegir", "q4-escala-proyeccion"]],
  ["u4", 9, ["q4-usuario-util"]],
  ["u4", 10, ["q4-lenguaje"]],
  ["u4", 11, []],
  ["u4", 12, ["c-elementos-mapa", "q4-canevas", "q4-leyenda", "p25-elementos"]],
  ["u4", 13, ["q4-base-tematica", "p25-vf-base", "v25-tematica"]],
  ["u4", 14, ["q4-ejemplo-helada"]],
  ["u4", 16, ["q4-generalizacion-escala", "q4-error-critico"]],
  ["u4", 17, ["q4-detalle-excesivo", "q4-limitaciones"]],
  ["u4", 18, ["e4-carretera"]],
  ["u4", 19, []],
  ["u4", 20, ["q4-gen-def"]],
  ["u4", 21, ["q4-operaciones", "q4-rendimiento"]],
  ["u4", 22, ["e4-op-ciudad", "e4-op-manzana", "e4-carretera-25000"]],
  ["u4", 23, ["e4-op-dos-carreteras"]],
  ["u4", 24, ["e4-op-tren", "e4-op-rio"]],
  ["u4", 25, ["e4-op-isla"]],
  ["u4", 26, ["q4-problematica", "q4-variedad-escalas", "c-generalizacion-tipos", "c-generalizacion-vuelo"]],
  ["u4", 27, ["q4-vuelo-inviable", "q4-vuelo-objetivo", "v25-al-vuelo"]],
  ["u4", 28, ["q4-multiescalar", "e4-nucleos", "p25-vf-multiescalar"]],
  ["u4", 29, []],
  ["u4", 30, ["q4-piramides", "q4-raster-objetivo"]],
  ["u4", 31, []],
  ["u4", 33, ["q4-fenomenos", "e4-volumetrico"]],
  ["u4", 34, ["q4-mapa-2d"]],
  ["u4", 35, []],
  ["u4", 36, ["q4-vv-def"]],
  ["u4", 37, []],
  ["u4", 38, ["q4-vv-lista", "e4-vv-columna"]],
  ["u4", 39, ["q4-posicion", "q4-tamano"]],
  ["u4", 40, []],
  ["u4", 41, ["q4-color", "e4-color-componente"]],
  ["u4", 42, ["q4-textura-forma"]],
  ["u4", 43, ["q4-simbolos-tipos"]],
  ["u4", 44, []],
  ["u4", 45, []],
  ["u4", 46, []],
  ["u4", 47, ["e4-simbolos-industrias"]],
  ["u4", 48, ["e4-asociativos"]],
  ["u4", 49, []],
  ["u4", 50, ["q4-propiedades", "q4-prop-selectiva", "q4-prop-asociativa"]],
  ["u4", 51, ["q4-niveles", "q4-seleccion-objetivo"]],
  ["u4", 52, ["q4-tabla-cuantitativa"]],
  ["u4", 53, ["q4-tipos-variables"]],
  ["u4", 54, ["e4-nominal", "e4-ordinal", "e4-intervalo", "e4-razon", "e4-alfanumerica", "p25-var-orden", "p25-var-razones", "p25-var-diferencias", "p25-var-identificacion", "p25-var-ejemplo"]],
  ["u4", 55, ["q4-operatividad"]],
  ["u4", 56, ["e4-mexico"]],
  ["u4", 57, ["q4-cuali-cuanti", "p25-comp-cuanti", "v25-comp-cuali"]],
  ["u4", 58, ["e4-valor-incorrecto"]],
  ["u4", 59, ["q4-tabla-relacion"]],
  ["u4", 60, ["q4-clases-porque"]],
  ["u4", 61, ["q4-parametros-clases"]],
  ["u4", 62, ["q4-intervalos-iguales", "q4-jenks", "q4-percentiles", "e4-amplitud"]],
  ["u4", 63, []],
  ["u4", 64, ["e4-cuartiles"]],
  ["u4", 65, ["e4-comparar-clases"]],
  ["u4", 66, ["e4-chaco"]],
  ["u4", 67, ["q4-tematicos"]],
  ["u4", 68, ["q4-graduados"]],
  ["u4", 69, ["q4-graduados-limites"]],
  ["u4", 70, []],
  ["u4", 71, []],
  ["u4", 72, ["e4-industrias-espana", "p25-mapa-a", "p25-dengue-info", "p25-dengue-vv", "p25-dengue-mapa"]],
  ["u4", 73, ["q4-puntos"]],
  ["u4", 74, ["q4-puntos-considerar", "e4-carga"]],
  ["u4", 75, ["p25-mapa-c"]],
  ["u4", 76, ["q4-flujos"]],
  ["u4", 77, ["p25-mapa-b"]],
  ["u4", 78, ["q4-isolineas"]],
  ["u4", 79, ["e4-isohietas"]],
  ["u4", 80, ["e4-fitogeografico"]],
  ["u4", 81, ["q4-coro-dasi-iso"]],
  ["u4", 82, ["e4-lluvias-categorias"]],
  ["u4", 83, ["e4-covid"]],
  ["u4", 84, ["e4-cartograma"]],
  ["u4", 85, []],
  // Unidad 4 · Conceptos cartográficos (IGN). Se saltean la portada y el índice (págs. 1 y 2)
  ["u4c", 3, ["c4-dos-problemas"]],
  ["u4c", 4, []],
  ["u4c", 5, ["c4-afilactica", "e4-proyeccion-proposito"]],
  ["u4c", 6, []],
  ["u4c", 7, []],
  ["u4c", 8, ["c4-conica-cilindrica"]],
  ["u4c", 9, []],
  ["u4c", 10, ["e4-escala-textual"]],
  ["u4c", 11, ["c4-pequena-grande", "c4-topo-tematico"]],
  ["u4c", 12, ["c4-imprescindibles"]],
  ["u4c", 13, []],
  ["u4c", 14, ["c4-dimensiones", "c4-ciudad-escala"]],
  ["u4c", 15, ["e4-espacio-temporal"]],
  ["u4c", 16, ["c4-continuos-discretos"]],
  ["u4c", 17, ["c4-cualitativo-lineal"]],
  ["u4c", 18, []],
  ["u4c", 19, ["c4-proporcionales"]],
  ["u4c", 20, ["c4-curvas-maestras"]],
  ["u4c", 21, ["c4-coropletas-cartogramas"]],
];

const porId = new Map(preguntas.map((p) => [p.id, p]));

export const RECORRIDO: Pagina[] = PAGINAS.map(([doc, n, ids]) => ({
  doc,
  n,
  unidad: DOCS[doc].unidad,
  src: `/slides/${doc}-${n}.jpg`,
  etiqueta: `${DOCS[doc].corto} · ${DOCS[doc].pagina} ${n}`,
  preguntas: ids.map((id) => {
    const p = porId.get(id);
    if (!p) throw new Error(`recorrido: no existe la pregunta ${id}`);
    return p;
  }),
}));

/** Cómo nombrar cada pregunta: "U1 · Pág. 13 · Pregunta 2". */
export const REFERENCIA: Record<string, string> = Object.fromEntries(
  RECORRIDO.flatMap((pag) => pag.preguntas.map((p, i) => [p.id, `${pag.etiqueta} · Pregunta ${i + 1}`])),
);
