import { preguntas, type Pregunta, type Unidad } from "./preguntas";

/**
 * Recorrido de lectura: las páginas de los PDFs en orden y, después de cada una,
 * las preguntas que salen de ella. Las páginas sin contenido (portadas, índices,
 * bibliografía) no figuran. Las imágenes se generan con scripts/generar-diapositivas.py.
 */
export type Doc = "u1" | "u2a" | "u2b" | "u3";

export const DOCS: Record<Doc, { unidad: Unidad; nombre: string; corto: string; pagina: string; vertical: boolean }> = {
  u1: { unidad: 1, nombre: "Unidad 1 · Contenidos", corto: "U1", pagina: "Pág.", vertical: true },
  u2a: { unidad: 2, nombre: "Unidad 2 · Parte 1", corto: "U2 P1", pagina: "Diap.", vertical: false },
  u2b: { unidad: 2, nombre: "Unidad 2 · Parte 2", corto: "U2 P2", pagina: "Diap.", vertical: false },
  u3: { unidad: 3, nombre: "Unidad 3", corto: "U3", pagina: "Diap.", vertical: false },
};

export type Pagina = {
  doc: Doc;
  n: number;
  unidad: Unidad;
  src: string;
  /** "U1 · Pág. 3" */
  etiqueta: string;
  preguntas: Pregunta[];
};

// [documento, página, ids de las preguntas en el orden en que se responden]
const PAGINAS: [Doc, number, string[]][] = [
  // Unidad 1 (revisada). Se saltea la pág. 15: anexo CORINE
  ["u1", 1, ["u1-def", "r-sig-generico", "u1-preguntas-sig", "c-categorias", "c-cat-localizacion", "c-cat-atributos", "c-cat-morfometria", "c-cat-analisis"]],
  ["u1", 2, ["u1-consulta-analisis", "u1-analisis", "u1-rutas", "u1-centros", "c-capacidades", "c-capacidades-vf", "r-def-modelo"]],
  ["u1", 3, ["r-ncgia", "u1-aplicaciones", "u1-antropica", "c-papeles", "c-papel-caso-particular", "c-papel-brotes", "c-papel-hospital", "c-papel-transporte", "c-papel-municipio", "c-papel-difusion"]],
  ["u1", 4, ["u1-ejemplos-concretos", "c-factores-clasificacion", "c-recursos-naturales", "c-riesgos", "u1-cotidiana", "c-dos-factores", "r-etapa-segunda", "r-etapa-tercera", "u1-etapas"]],
  ["u1", 5, ["u1-snow", "u1-cgis"]],
  ["u1", 6, ["r-dime-topologia", "r-symap-grid"]],
  ["u1", 7, []],
  ["u1", 8, ["u1-ogc"]],
  ["u1", 9, []],
  ["u1", 10, []],
  ["u1", 11, []],
  ["u1", 12, []],
  ["u1", 13, ["u1-componentes", "u1-hardware", "r-hardware-rango", "u1-software", "u1-datos-importante", "u1-datos-origen", "r-datos-compromiso"]],
  ["u1", 14, ["u1-personal-vf", "r-usuarios", "c-motor-sig", "c-personal-perfiles", "u1-metodos", "c-elementos-sistema", "c-olaya"]],
  // Unidad 2 · parte 1 (revisada). Se saltean la portada, el índice y las fuentes (diap. 1, 2 y 76)
  ["u2a", 3, ["r-diferenciador"]],
  ["u2a", 4, ["u2-componentes-info"]],
  ["u2a", 5, ["r-parcela"]],
  ["u2a", 6, ["r-compleja"]],
  ["u2a", 7, []],
  ["u2a", 8, []],
  ["u2a", 9, ["u2-division-horizontal"]],
  ["u2a", 10, ["r-categorias"]],
  ["u2a", 11, []],
  ["u2a", 12, []],
  ["u2a", 13, ["u2-capas-mapa"]],
  ["u2a", 14, []],
  ["u2a", 15, ["u2-capas"]],
  ["u2a", 16, []],
  ["u2a", 17, ["u2-problema"]],
  ["u2a", 18, ["r-mayor-abstraccion", "r-menor-abstraccion", "u2-niveles", "r-def-representacion", "r-def-almacenamiento"]],
  ["u2a", 19, ["r-paradigmas", "u2-dimensiones", "u2-regla-oro"]],
  ["u2a", 20, []],
  ["u2a", 21, ["u2-campo-def"]],
  ["u2a", 22, []],
  ["u2a", 23, ["u2-viento", "r-termino-vectorial"]],
  ["u2a", 24, ["r-origen", "u2-origen"]],
  ["u2a", 25, ["u2-discretas", "c-cruce-calles", "r-nominal", "u2-escalares"]],
  ["u2a", 26, ["u2-asociacion"]],
  ["u2a", 27, ["u2-elev-tin", "r-elev-malla"]],
  ["u2a", 28, ["u2-red-raster", "r-red-vector"]],
  ["u2a", 29, []],
  ["u2a", 30, []],
  ["u2a", 31, ["u2-elev-curvas"]],
  ["u2a", 32, []],
  ["u2a", 33, ["u2-raster-espacio"]],
  ["u2a", 34, ["u2-sistematicidad"]],
  ["u2a", 35, ["u2-definir-raster", "e-raster-elev"]],
  ["u2a", 36, []],
  ["u2a", 37, ["u2-malla-coords", "e-raster-coord"]],
  ["u2a", 38, ["u2-resolucion-factores", "u2-resolucion-calc", "e-raster-area"]],
  ["u2a", 39, []],
  ["u2a", 40, ["u2-resolucion"]],
  ["u2a", 41, ["u2-elev-puntos", "u2-raster-analisis"]],
  ["u2a", 42, ["r-imagenes", "u2-imagenes-bandas"]],
  ["u2a", 43, []],
  ["u2a", 44, ["u2-primitivas"]],
  ["u2a", 45, ["u2-ciudad"]],
  ["u2a", 46, ["r-forma-primitiva", "u2-vector-campos"]],
  ["u2a", 47, []],
  ["u2a", 48, ["u2-tematica-enlace", "r-raster-sin-bd"]],
  ["u2a", 49, ["u2-tipo-analisis-2", "r-analisis-espacial", "u2-tipo-analisis"]],
  ["u2a", 50, []],
  ["u2a", 51, ["r-topo-reglas"]],
  ["u2a", 52, ["u2-topologia-def", "r-cartografica"]],
  ["u2a", 53, []],
  ["u2a", 54, ["u2-topo-importancia"]],
  ["u2a", 55, []],
  ["u2a", 56, ["u2-redes"]],
  ["u2a", 57, ["r-topo-calidad"]],
  ["u2a", 58, ["u2-edicion"]],
  ["u2a", 59, ["u2-topologia-raster"]],
  ["u2a", 60, []],
  ["u2a", 61, []],
  ["u2a", 62, ["u2-spaghetti"]],
  ["u2a", 63, ["u2-sin-topo-razones"]],
  ["u2a", 64, ["u2-areas-influencia"]],
  ["u2a", 65, ["u2-diccionario"]],
  ["u2a", 66, ["u2-dime"]],
  ["u2a", 67, ["u2-arconodo-elementos"]],
  ["u2a", 68, ["u2-arconodo-tabla"]],
  ["u2a", 69, ["r-dime-arconodo"]],
  ["u2a", 70, ["r-conectividad", "r-adyacencia"]],
  ["u2a", 71, ["u2-relaciones", "r-inclusion"]],
  ["u2a", 72, ["u2-matriz-sintesis"]],
  ["u2a", 73, ["u2-imprecision"]],
  ["u2a", 74, ["u2-no-idoneo"]],
  ["u2a", 75, ["u2-cuando-usar", "u2-cuando-vectorial"]],
  // Unidad 2 · parte 2 (revisada). Se saltean la portada, los títulos de sección y el enlace a PostGIS (diap. 1, 2, 27 y 30)
  ["u2b", 3, []],
  ["u2b", 4, ["u2b-necesidades"]],
  ["u2b", 5, ["u2b-raster-simple"]],
  ["u2b", 6, ["u2b-matriz-ventajas"]],
  ["u2b", 7, ["u2b-raster-matriz", "c-compresion"]],
  ["u2b", 8, []],
  ["u2b", 9, ["u2b-bip", "u2b-bil", "e-bsq"]],
  ["u2b", 10, ["u2b-vectorial"]],
  ["u2b", 11, []],
  ["u2b", 12, ["u2b-indices"]],
  ["u2b", 13, ["u2b-indexacion"]],
  ["u2b", 14, ["u2b-rtree"]],
  ["u2b", 15, ["r-formatos-vector"]],
  ["u2b", 16, ["r-bd-espaciales"]],
  ["u2b", 17, ["r-formatos-raster", "u2b-raster-formatos"]],
  ["u2b", 18, []],
  ["u2b", 19, ["u2b-shapefile"]],
  ["u2b", 20, ["u2b-prj"]],
  ["u2b", 21, ["r-gml"]],
  ["u2b", 22, []],
  ["u2b", 23, ["r-kml"]],
  ["u2b", 24, ["u2b-kml"]],
  ["u2b", 25, []],
  ["u2b", 26, ["u2b-geojson"]],
  ["u2b", 28, []],
  ["u2b", 29, ["u2b-sdbms", "r-tablas-gd"]],
  ["u2b", 31, []],
  ["u2b", 32, ["r-postgis"]],
  ["u2b", 33, []],
  ["u2b", 34, ["r-sfs"]],
  // Unidad 3 (revisada). Se saltean la portada, la ilustración de apertura y los títulos de sección (diap. 1, 2, 7, 14, 37, 45 y 69)
  ["u3", 3, ["r-geodesia-def"]],
  ["u3", 4, ["u3-geodesia-tipos"]],
  ["u3", 5, []],
  ["u3", 6, ["u3-cartografia-def"]],
  ["u3", 8, ["r-edicion", "r-problema-proyecciones"]],
  ["u3", 9, ["u3-problemas-cartografia", "c-generalizacion-def", "c-generalizacion-tipos", "c-generalizacion-vuelo", "r-diseno"]],
  ["u3", 10, []],
  ["u3", 11, ["c-elementos-mapa"]],
  ["u3", 12, ["e-escala-tipo"]],
  ["u3", 13, ["u3-escala-tipos", "e-escala-representaciones", "u3-escala-unidad", "e-escala-2cm", "u3-escala-calc", "e-escala-real", "e-escala-mapa", "e-escala-grafica", "e-escala-comparar"]],
  ["u3", 15, []],
  ["u3", 16, ["u3-forma"]],
  ["u3", 17, []],
  ["u3", 18, []],
  ["u3", 19, ["u3-por-que-forma"]],
  ["u3", 20, []],
  ["u3", 21, ["u3-geoide"]],
  ["u3", 22, ["u3-geoide-razon"]],
  ["u3", 23, []],
  ["u3", 24, []],
  ["u3", 25, []],
  ["u3", 26, ["u3-geoide-insuficiente"]],
  ["u3", 27, ["r-elipsoide-def"]],
  ["u3", 28, ["r-semiejes", "u3-elipse-params"]],
  ["u3", 29, []],
  ["u3", 30, ["e-elipsoide-b"]],
  ["u3", 31, []],
  ["u3", 32, ["u3-capas-tierra"]],
  ["u3", 33, ["r-no-coinciden", "r-desviacion"]],
  ["u3", 34, []],
  ["u3", 35, []],
  ["u3", 36, ["u3-latlon"]],
  ["u3", 38, ["u3-sistema-def"]],
  ["u3", 39, ["u3-local-vf"]],
  ["u3", 40, ["u3-datum"]],
  ["u3", 41, []],
  ["u3", 42, ["u3-global"]],
  ["u3", 43, []],
  ["u3", 44, ["u3-marco"]],
  ["u3", 46, ["r-proyeccion-def"]],
  ["u3", 47, []],
  ["u3", 48, ["u3-distorsiones"]],
  ["u3", 49, ["u3-escala-nominal"]],
  ["u3", 50, []],
  ["u3", 51, ["r-tipos-proyecciones"]],
  ["u3", 52, ["r-conformes"]],
  ["u3", 53, ["r-equivalentes", "u3-mercator"]],
  ["u3", 54, ["u3-equidistante"]],
  ["u3", 55, ["u3-desarrollables", "u3-contacto"]],
  ["u3", 56, []],
  ["u3", 57, ["u3-conicas"]],
  ["u3", 58, ["u3-cilindricas"]],
  ["u3", 59, []],
  ["u3", 60, ["u3-aspecto"]],
  ["u3", 61, []],
  ["u3", 62, ["u3-perspectivas", "r-estereografica", "r-ortografica"]],
  ["u3", 63, ["r-epsg-problema"]],
  ["u3", 64, ["r-crs-srs", "u3-reproyeccion"]],
  ["u3", 65, ["u3-epsg-def"]],
  ["u3", 66, []],
  ["u3", 67, ["r-epsg-4326"]],
  ["u3", 68, ["u3-epsg-4326"]],
  ["u3", 70, []],
  ["u3", 71, ["u3-tyson"]],
  ["u3", 72, []],
  ["u3", 73, ["r-utm-ventaja", "r-utm-desventaja"]],
  ["u3", 74, ["u3-utm", "e-utm-zona"]],
  ["u3", 75, ["u3-argentina", "r-faja-ancho", "u3-chaco"]],
  ["u3", 76, ["e-gk-faja"]],
  ["u3", 77, ["u3-proj4-posgar", "e-gk-x"]],
  ["u3", 78, ["r-posgar-inchauspe"]],
  ["u3", 79, ["r-mismo-punto"]],
];

const porId = new Map(preguntas.map((p) => [p.id, p]));

export const RECORRIDO: Pagina[] = PAGINAS.map(([doc, n, ids]) => ({
  doc,
  n,
  unidad: DOCS[doc].unidad,
  src: `/slides/${doc}-${n}.jpg`,
  etiqueta: `${DOCS[doc].corto} · ${DOCS[doc].pagina} ${n}`,
  preguntas: ids.map((id) => {
    const p = porId.get(id);
    if (!p) throw new Error(`recorrido: no existe la pregunta ${id}`);
    return p;
  }),
}));

/** Cómo nombrar cada pregunta: "U1 · Pág. 13 · Pregunta 2". */
export const REFERENCIA: Record<string, string> = Object.fromEntries(
  RECORRIDO.flatMap((pag) => pag.preguntas.map((p, i) => [p.id, `${pag.etiqueta} · Pregunta ${i + 1}`])),
);
